//! The `conformance` verb — in-situ probeability (rules P-f, P-g, P-h).
//!
//! rf ships as a crates.io binary, so a consumer holds an instance they did not
//! build. This verb lets them verify the contract from the deployed vantage: it
//! runs the `release-self-check` profile by spawning THIS binary on its own
//! declared surface, adjudicates each probe to pass / fail / not-applicable with
//! a reason, and returns the verdict set under the required schema floor.
//!
//! Cases are generated by folding over rf's real surface (the verbs, the arity-1
//! flags), never hand-listed. Cases whose surface rf does not have — an injection
//! trigger, a parser-derived manifest, enum flags, a machine help surface — are
//! recorded not-applicable with a reason, never silently skipped.

use crate::capabilities;
use crate::envelope::{envelope, err};
use serde_json::{Map, Value};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;
use std::process::Command;

const PROFILE: &str = "release-self-check";
const SEVEN: [&str; 7] = [
    "ok",
    "tool_version",
    "data",
    "meta",
    "warnings",
    "commands",
    "errors",
];

/// One observed probe invocation of the rf binary.
struct Probe {
    exit: i32,
    ok: Option<bool>,
    err0: Option<String>,
    request_id: Option<String>,
    seven: bool,
    stdout_nonempty: bool,
}

fn run_probe(exe: &Path, args: &[&str]) -> Probe {
    run_probe_env(exe, args, None)
}

/// Run a probe with explicit control over the fault seam. `fault: None` strips any
/// ambient `RF_FAULT` so a normal probe is never perturbed by the caller's env;
/// `fault: Some(stage)` sets it, to exercise that stage's injection seam.
fn run_probe_env(exe: &Path, args: &[&str], fault: Option<&str>) -> Probe {
    let mut cmd = Command::new(exe);
    cmd.args(args).env("NO_COLOR", "1");
    match fault {
        Some(stage) => {
            cmd.env("RF_FAULT", stage);
        }
        None => {
            cmd.env_remove("RF_FAULT");
        }
    }
    match cmd.output() {
        Ok(o) => {
            let v: Option<Value> = serde_json::from_slice(&o.stdout).ok();
            let get_str = |path: &[&str]| -> Option<String> {
                let mut cur = v.as_ref()?;
                for k in path {
                    cur = cur.get(*k)?;
                }
                cur.as_str().map(String::from)
            };
            Probe {
                exit: o.status.code().unwrap_or(-1),
                ok: v
                    .as_ref()
                    .and_then(|x| x.get("ok"))
                    .and_then(Value::as_bool),
                err0: v
                    .as_ref()
                    .and_then(|x| x.get("errors"))
                    .and_then(Value::as_array)
                    .and_then(|a| a.first())
                    .and_then(|e| e.get("code"))
                    .and_then(Value::as_str)
                    .map(String::from),
                request_id: get_str(&["meta", "request_id"]),
                seven: v
                    .as_ref()
                    .map(|x| SEVEN.iter().all(|k| x.get(*k).is_some()))
                    .unwrap_or(false),
                stdout_nonempty: !o.stdout.is_empty(),
            }
        }
        Err(_) => Probe {
            exit: -1,
            ok: None,
            err0: None,
            request_id: None,
            seven: false,
            stdout_nonempty: false,
        },
    }
}

/// The composite instance id: label, then sorted `key=value` segments joined by
/// `::` (the probeability contract's instance-id grammar). Sorting makes the id
/// independent of iteration order so a pinned diff shows surface changes only.
fn cid(label: &str, target: &[(&str, &str)]) -> String {
    let mut segs: Vec<String> = target.iter().map(|(k, v)| format!("{k}={v}")).collect();
    segs.sort();
    let mut s = String::from(label);
    for seg in segs {
        s.push_str("::");
        s.push_str(&seg);
    }
    s
}

fn target_obj(target: &[(&str, &str)]) -> Value {
    let mut m = Map::new();
    for (k, v) in target {
        m.insert((*k).into(), Value::from(*v));
    }
    Value::from(m)
}

/// Deterministic placeholder id for a case with no single probe invocation
/// (aggregate or not-applicable), so `request_id` is never null.
fn synth_id(case_id: &str) -> String {
    let hex: String = Sha256::digest(case_id.as_bytes())
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect();
    hex[..16].to_string()
}

fn vd(pass: bool) -> &'static str {
    if pass {
        "pass"
    } else {
        "fail"
    }
}

/// Argv that reaches a given stage's injection seam with otherwise-valid input,
/// so the only thing that can fault is the seam itself.
fn stage_argv(stage: &str) -> Vec<&'static str> {
    match stage {
        // content and engine share the content path; engine faults deeper in it.
        "content" | "engine" => vec![
            "content",
            "zzq_no_such_token",
            "/rf-conformance-empty",
            "--json",
        ],
        "find" => vec![
            "find",
            "zzq_no_such_token",
            "/rf-conformance-empty",
            "--name",
            "conf",
            "--json",
        ],
        "doctor" => vec!["doctor", ".", "--json"],
        _ => vec!["capabilities", "--json"],
    }
}

/// A probe of an injected stage produced a *total* error envelope: the totality
/// wrapper converted the panic into exit 6 + INTERNAL + the full seven keys,
/// rather than letting an unmediated crash escape.
fn is_total_fault(p: &Probe) -> bool {
    p.exit == 6 && p.ok == Some(false) && p.err0.as_deref() == Some("INTERNAL") && p.seven
}

/// Every declared spelling maps to the arity enforced by its source. Comparing
/// spelling+arity catches aliases and value-taking flags, not only primary names.
fn flag_arities(v: &Value) -> BTreeMap<String, i64> {
    v.get("flags")
        .and_then(Value::as_array)
        .map(|a| {
            a.iter()
                .flat_map(|e| {
                    let arity = e.get("arity").and_then(Value::as_i64).unwrap_or(0);
                    std::iter::once(&e["name"])
                        .chain(e["aliases"].as_array().into_iter().flatten())
                        .filter_map(Value::as_str)
                        .map(String::from)
                        .map(move |name| (name, arity))
                })
                .collect()
        })
        .unwrap_or_default()
}

/// Positional-argument names of one verb. The hand surface lists them under
/// `args` as objects with `name`; the parser manifest lists them under
/// `positionals` as bare strings.
fn positional_names(v: &Value) -> BTreeSet<String> {
    let from_args = v.get("args").and_then(Value::as_array).map(|a| {
        a.iter()
            .filter_map(|e| e.get("name").and_then(Value::as_str).map(String::from))
            .collect::<BTreeSet<String>>()
    });
    let from_pos = v.get("positionals").and_then(Value::as_array).map(|a| {
        a.iter()
            .filter_map(|e| e.as_str().map(String::from))
            .collect::<BTreeSet<String>>()
    });
    from_args.or(from_pos).unwrap_or_default()
}

/// True iff the hand-kept `verbs` surface and the parser-derived manifest agree
/// on the verb set and, per verb, the long-flag names and positional names.
fn reconcile(
    hand: &Map<String, Value>,
    derived: &Map<String, Value>,
    hand_globals: &Value,
    derived_globals: &Value,
) -> bool {
    let hverbs: BTreeSet<&String> = hand.keys().collect();
    let dverbs: BTreeSet<&String> = derived.keys().collect();
    if hverbs != dverbs {
        return false;
    }
    let globals = |flags: &Value| {
        flag_arities(&Value::Object(
            [("flags".to_string(), flags.clone())].into_iter().collect(),
        ))
    };
    globals(hand_globals) == globals(derived_globals)
        && hand.iter().all(|(name, hv)| {
            let dv = &derived[name];
            let aliases = |v: &Value| {
                v["aliases"]
                    .as_array()
                    .into_iter()
                    .flatten()
                    .filter_map(Value::as_str)
                    .map(String::from)
                    .collect::<BTreeSet<_>>()
            };
            flag_arities(hv) == flag_arities(dv)
                && positional_names(hv) == positional_names(dv)
                && aliases(hv) == aliases(dv)
        })
}

/// Accumulates case rows and the cross-case observations X-06 / S-03 / S-04 need.
struct Sweep {
    rows: Vec<Value>,
    exit_codes: BTreeSet<i32>,
    err_codes: BTreeSet<String>,
    machine_stdout_all_nonempty: bool,
    exit_and_doc_together: bool,
}

impl Sweep {
    fn new() -> Self {
        Sweep {
            rows: vec![],
            exit_codes: BTreeSet::new(),
            err_codes: BTreeSet::new(),
            machine_stdout_all_nonempty: true,
            exit_and_doc_together: true,
        }
    }

    /// Record a machine-rendering probe's codes and totality signals.
    fn observe(&mut self, p: &Probe) {
        self.exit_codes.insert(p.exit);
        if let Some(code) = &p.err0 {
            self.err_codes.insert(code.clone());
        }
        if !p.stdout_nonempty {
            self.machine_stdout_all_nonempty = false;
            self.exit_and_doc_together = false;
        }
    }

    fn case(
        &mut self,
        label: &str,
        target: &[(&str, &str)],
        verdict: &str,
        reason: Option<&str>,
        request_id: Option<&str>,
    ) {
        let id = cid(label, target);
        let rid = request_id
            .map(String::from)
            .unwrap_or_else(|| synth_id(&id));
        let mut m = Map::new();
        m.insert("case_id".into(), Value::from(id));
        m.insert("verdict".into(), Value::from(verdict));
        m.insert(
            "reason".into(),
            reason.map(Value::from).unwrap_or(Value::Null),
        );
        m.insert("request_id".into(), Value::from(rid));
        m.insert("target".into(), target_obj(target));
        self.rows.push(Value::from(m));
    }
}

pub fn run() -> (Value, i32) {
    let exe = match std::env::current_exe() {
        Ok(p) => p,
        Err(e) => {
            let mut meta = Map::new();
            meta.insert("verb".into(), Value::from("conformance"));
            return (
                envelope(
                    false,
                    vec![],
                    meta,
                    vec![],
                    vec![],
                    vec![err("INTERNAL", format!("cannot resolve own path: {e}"))],
                ),
                6,
            );
        }
    };

    let caps = capabilities::build();
    let mut s = Sweep::new();

    // Minimal valid argv per verb (a happy path that needs no external corpus).
    let exe_arg = exe.to_string_lossy().into_owned();
    let happy: Vec<(&str, Vec<&str>)> = vec![
        ("robot-docs", vec!["robot-docs", "guide", "--json"]),
        ("capabilities", vec!["capabilities", "--json"]),
        (
            "content",
            vec![
                "content",
                "zzq_no_such_token",
                "/rf-conformance-empty",
                "--json",
            ],
        ),
        (
            "find",
            vec![
                "find",
                "zzq_no_such_token",
                "/rf-conformance-empty",
                "--name",
                "conf",
                "--json",
            ],
        ),
        ("doctor", vec!["doctor", ".", "--json"]),
        ("why", vec!["why", "zzq_no_such_token", &exe_arg, "--json"]),
    ];

    // ---- Group 1: base cases (adjudicated against rf's declared contract) ----

    // B-01: unrecognized verb -> exit 1, ok:false, UNKNOWN_COMMAND, full envelope.
    {
        let p = run_probe(&exe, &["nosuchverb"]);
        s.observe(&p);
        let pass = p.exit == 1
            && p.ok == Some(false)
            && p.err0.as_deref() == Some("UNKNOWN_COMMAND")
            && p.seven;
        s.case(
            "B-01",
            &[("verb", "nosuchverb")],
            vd(pass),
            None,
            p.request_id.as_deref(),
        );
    }

    // B-03: unrecognized verb-local flag on every verb -> exit 1, UNKNOWN_FLAG.
    for (verb, base) in &happy {
        let mut args: Vec<&str> = base.iter().copied().filter(|a| *a != "--json").collect();
        args.push("--bogus");
        let p = run_probe(&exe, &args);
        s.observe(&p);
        let pass = p.exit == 1
            && p.ok == Some(false)
            && p.err0.as_deref() == Some("UNKNOWN_FLAG")
            && p.seven;
        s.case(
            "B-03",
            &[("verb", verb), ("flag", "--bogus")],
            vd(pass),
            None,
            p.request_id.as_deref(),
        );
    }

    // B-07: a value-taking flag as the final token -> exit 1, INVALID_INPUT. Folds over
    // find's arity-1 flags.
    let arity1: [(&str, Vec<&str>); 3] = [
        ("--name", vec!["find", "x", ".", "--name"]),
        (
            "--structural",
            vec!["find", "x", ".", "--name", "conf", "--structural"],
        ),
        ("--lang", vec!["find", "x", ".", "--name", "conf", "--lang"]),
    ];
    for (flag, args) in &arity1 {
        let p = run_probe(&exe, args);
        s.observe(&p);
        let pass = p.exit == 1
            && p.ok == Some(false)
            && p.err0.as_deref() == Some("INVALID_INPUT")
            && p.seven;
        s.case(
            "B-07",
            &[("verb", "find"), ("flag", flag)],
            vd(pass),
            None,
            p.request_id.as_deref(),
        );
    }

    // R-01: a syntactically invalid regex -> exit 1, BAD_PATTERN. rf-specific
    // domain fault; folds over the search verbs.
    let badpat: Vec<(&str, Vec<&str>)> = vec![
        ("content", vec!["content", "[", "."]),
        ("find", vec!["find", "[", ".", "--name", "conf"]),
        ("why", vec!["why", "[", &exe_arg]),
    ];
    for (verb, args) in &badpat {
        let p = run_probe(&exe, args);
        s.observe(&p);
        let pass = p.exit == 1
            && p.ok == Some(false)
            && p.err0.as_deref() == Some("BAD_PATTERN")
            && p.seven;
        s.case(
            "R-01",
            &[("verb", verb)],
            vd(pass),
            None,
            p.request_id.as_deref(),
        );
    }

    // T-01/T-02: why validates target inputs before compiling a pattern.
    for (id, args) in [
        ("T-01", vec!["why", "x", "."]),
        ("T-02", vec!["why", "x", "/rf-conformance-missing-target"]),
        ("T-03", vec!["why", "[", "/rf-conformance-missing-target"]),
    ] {
        let p = run_probe(&exe, &args);
        s.observe(&p);
        let pass = p.exit == 1
            && p.ok == Some(false)
            && p.err0.as_deref() == Some("INVALID_TARGET")
            && p.seven;
        s.case(
            id,
            &[("verb", "why")],
            vd(pass),
            None,
            p.request_id.as_deref(),
        );
    }

    // R-02: --structural without --lang -> exit 1, USAGE (rf's documented guard).
    {
        let p = run_probe(
            &exe,
            &["find", "x", ".", "--name", "conf", "--structural", "f($$$)"],
        );
        s.observe(&p);
        let pass =
            p.exit == 1 && p.ok == Some(false) && p.err0.as_deref() == Some("USAGE") && p.seven;
        s.case(
            "R-02",
            &[("verb", "find")],
            vd(pass),
            None,
            p.request_id.as_deref(),
        );
    }

    // ---- Group 2: mode matrix (rf has one machine shape: the envelope) ----

    // M-01: every happy path parses as JSON with all seven envelope keys, ok:true.
    for (verb, args) in &happy {
        let p = run_probe(&exe, args);
        s.observe(&p);
        let pass = p.exit == 0 && p.ok == Some(true) && p.seven;
        s.case(
            "M-01",
            &[("verb", verb), ("shape", "envelope")],
            vd(pass),
            None,
            p.request_id.as_deref(),
        );
    }

    // ---- Group 3: structural / totality ----

    // S-01, S-02: per-stage fault injection (P-d). With the seam compiled in,
    // inject a real fault at a stage and assert the totality wrapper converts the
    // panic into a total error envelope. With the seam absent (the release build),
    // there is no trigger to pull, so these stay honestly not-applicable.
    if crate::fault::SEAM_PRESENT {
        let p = run_probe_env(&exe, &stage_argv("content"), Some("content"));
        s.observe(&p);
        s.case(
            "S-01",
            &[("stage", "content")],
            vd(is_total_fault(&p)),
            None,
            p.request_id.as_deref(),
        );
        let p = run_probe_env(&exe, &stage_argv("find"), Some("find"));
        s.observe(&p);
        s.case(
            "S-02",
            &[("stage", "find")],
            vd(is_total_fault(&p)),
            None,
            p.request_id.as_deref(),
        );
    } else {
        s.case(
            "S-01",
            &[],
            "not_applicable",
            Some("release-build-fault-trigger-unavailable"),
            None,
        );
        s.case(
            "S-02",
            &[],
            "not_applicable",
            Some("release-build-fault-trigger-unavailable"),
            None,
        );
    }

    // ---- Group 4: successful special surfaces ----

    // H-01: bare invocation. rf requires a subcommand and declares no bare success
    // surface, so the contract's exit-0 usage case does not apply.
    s.case(
        "H-01",
        &[],
        "not_applicable",
        Some("rf-requires-a-subcommand"),
        None,
    );

    // H-02: --help and --version -> human text, exit 0.
    for (surface, arg) in [("help", "--help"), ("version", "--version")] {
        let p = run_probe(&exe, &[arg]);
        // human surface: assert exit 0 and non-empty stdout, not JSON shape.
        let pass = p.exit == 0 && p.stdout_nonempty;
        if !p.stdout_nonempty {
            s.exit_and_doc_together = false;
        }
        s.exit_codes.insert(p.exit);
        s.case(
            "H-02",
            &[("surface", surface)],
            vd(pass),
            None,
            p.request_id.as_deref(),
        );
    }

    // H-03: help under a machine selector. rf renders help as clap human text with
    // no envelope form, so a machine help surface does not apply.
    s.case(
        "H-03",
        &[],
        "not_applicable",
        Some("help-surface-not-machine-rendered"),
        None,
    );

    // B-13: a positional whose text is a flag, after `--`, is treated as data.
    {
        let p = run_probe(&exe, &["doctor", "--", "--json"]);
        s.observe(&p);
        let pass = p.exit == 0 && p.ok == Some(true) && p.seven;
        s.case(
            "B-13",
            &[("token", "--json")],
            vd(pass),
            None,
            p.request_id.as_deref(),
        );
    }

    // ---- Group 3 aggregates (computed after every machine probe ran) ----

    // S-03: no machine-rendering argv produced zero bytes on stdout.
    s.case("S-03", &[], vd(s.machine_stdout_all_nonempty), None, None);
    // S-04: every invocation produced an exit code and a document together.
    s.case("S-04", &[], vd(s.exit_and_doc_together), None, None);

    // ---- Group 5: the probe surface ----

    // X-01: reconcile the hand-kept `verbs` surface against the parser-derived
    // manifest (both published in capabilities). Independent sources for the same
    // surface; a flag or verb changed on one side only fails here instead of
    // shipping a contract that disagrees with the real parser.
    {
        let hand = caps.get("verbs").and_then(Value::as_object);
        let manifest = caps.get("parser_manifest");
        let derived = manifest
            .and_then(|m| m.get("commands"))
            .and_then(Value::as_object);
        let pass = matches!((hand, derived, manifest), (Some(h), Some(d), Some(m)) if reconcile(
            h,
            d,
            caps.get("global_flags").unwrap_or(&Value::Null),
            m.get("global_flags").unwrap_or(&Value::Null),
        ));
        s.case("X-01", &[], vd(pass), None, None);
    }
    // X-02: the seam is *per-stage* and total across every stage, not just one.
    // Fold over the declared stage list; each injected fault must be total. Absent
    // the seam (release build), there is nothing to enumerate -> not-applicable.
    if crate::fault::SEAM_PRESENT {
        let all_total = crate::fault::STAGES.iter().all(|stage| {
            let p = run_probe_env(&exe, &stage_argv(stage), Some(stage));
            let total = is_total_fault(&p);
            s.observe(&p);
            total
        });
        s.case("X-02", &[("stages", "all")], vd(all_total), None, None);
    } else {
        s.case(
            "X-02",
            &[],
            "not_applicable",
            Some("release-build-fault-trigger-unavailable"),
            None,
        );
    }

    // X-03: release posture. In a release build the seam is compiled out and no
    // injection trigger is declared in capabilities.env_vars; passing means the
    // build has no live trigger, which is what lets S-01/S-02/X-02 be honestly
    // not-applicable. A fault-injection build deliberately violates that posture,
    // so the release-posture claim does not apply to it.
    if crate::fault::SEAM_PRESENT {
        s.case(
            "X-03",
            &[],
            "not_applicable",
            Some("fault-injection-build-not-release-posture"),
            None,
        );
    } else {
        let env_vars = caps
            .get("env_vars")
            .and_then(Value::as_array)
            .cloned()
            .unwrap_or_default();
        let declares_trigger = env_vars.iter().filter_map(Value::as_str).any(|v| {
            let u = v.to_ascii_uppercase();
            u.contains("FAULT") || u.contains("_TEST") || u.contains("INJECT")
        });
        s.case(
            "X-03",
            &[("posture", "compiled-out")],
            vd(!declares_trigger),
            None,
            None,
        );
    }

    // X-06: every exit code and error code observed in this sweep is declared.
    {
        let declared_exit: BTreeSet<i32> = caps
            .get("exit_codes")
            .and_then(Value::as_object)
            .map(|o| o.keys().filter_map(|k| k.parse::<i32>().ok()).collect())
            .unwrap_or_default();
        let declared_err: BTreeSet<String> = caps
            .get("error_codes")
            .and_then(Value::as_object)
            .map(|o| o.keys().cloned().collect())
            .unwrap_or_default();
        let exits_ok = s.exit_codes.iter().all(|c| declared_exit.contains(c));
        let errs_ok = s.err_codes.iter().all(|c| declared_err.contains(c));
        s.case("X-06", &[], vd(exits_ok && errs_ok), None, None);
    }

    // X-07: value-domain probes are generated from the hand-declared domain
    // registry. Each entry supplies one accepted and one rejected value.
    for domain in caps["value_domains"].as_array().into_iter().flatten() {
        let command = domain["command"].as_str().unwrap_or("");
        let flag = domain["flag"].as_str().unwrap_or("");
        let accepted = domain["accepted"].as_str().unwrap_or("");
        let rejected = domain["rejected"].as_str().unwrap_or("");
        let error_code = domain["error_code"].as_str().unwrap_or("INVALID_INPUT");
        let accepted_args = [
            command,
            "zzq_no_such_token",
            "/rf-conformance-empty",
            flag,
            accepted,
            "--json",
        ];
        let rejected_args = [
            command,
            "zzq_no_such_token",
            "/rf-conformance-empty",
            flag,
            rejected,
            "--json",
        ];
        let good = run_probe(&exe, &accepted_args);
        let bad = run_probe(&exe, &rejected_args);
        s.observe(&good);
        s.observe(&bad);
        s.case(
            "X-07",
            &[("flag", flag), ("value", "accepted")],
            vd(good.exit == 0 && good.ok == Some(true) && good.seven),
            None,
            good.request_id.as_deref(),
        );
        s.case(
            "X-07",
            &[("flag", flag), ("value", "rejected")],
            vd(bad.exit == 1
                && bad.ok == Some(false)
                && bad.err0.as_deref() == Some(error_code)
                && bad.seven),
            None,
            bad.request_id.as_deref(),
        );
    }

    // X-05: this verb's own result meets the floor. Adjudicated on the rows built
    // so far: each carries the five required keys, and target agrees with case_id.
    {
        let pass = s.rows.iter().all(|r| {
            let has = |k: &str| r.get(k).map(|v| !v.is_null()).unwrap_or(false);
            let id = r.get("case_id").and_then(Value::as_str).unwrap_or("");
            let target_agrees = r
                .get("target")
                .and_then(Value::as_object)
                .map(|t| {
                    t.iter().all(|(k, v)| {
                        v.as_str()
                            .map(|vs| id.contains(&format!("{k}={vs}")))
                            .unwrap_or(false)
                    })
                })
                .unwrap_or(false);
            has("case_id")
                && has("verdict")
                && has("request_id")
                && r.get("target").is_some()
                && target_agrees
        });
        s.case("X-05", &[("verb", "conformance")], vd(pass), None, None);
    }

    // ---- assemble ----
    let mut rows = s.rows;
    rows.sort_by(|a, b| {
        a["case_id"]
            .as_str()
            .unwrap_or("")
            .cmp(b["case_id"].as_str().unwrap_or(""))
    });

    let mut pass = 0i64;
    let mut fail = 0i64;
    let mut na = 0i64;
    for r in &rows {
        match r["verdict"].as_str().unwrap_or("") {
            "pass" => pass += 1,
            "fail" => fail += 1,
            "not_applicable" => na += 1,
            _ => {}
        }
    }

    let mut counts = Map::new();
    counts.insert("pass".into(), Value::from(pass));
    counts.insert("fail".into(), Value::from(fail));
    counts.insert("not_applicable".into(), Value::from(na));

    let failed_ids: Vec<String> = rows
        .iter()
        .filter(|row| row["verdict"] == "fail")
        .filter_map(|row| row["case_id"].as_str().map(String::from))
        .collect();
    let mut payload = Map::new();
    payload.insert("profile".into(), Value::from(PROFILE));
    payload.insert("counts".into(), Value::from(counts));
    payload.insert("cases".into(), Value::from(rows));

    let mut meta = Map::new();
    meta.insert("verb".into(), Value::from("conformance"));
    meta.insert("profile".into(), Value::from(PROFILE));
    meta.insert(
        "headline".into(),
        Value::from(format!("{pass} pass, {fail} fail, {na} n/a")),
    );

    let ok = fail == 0;
    let errors = if ok {
        vec![]
    } else {
        vec![err(
            "CONFORMANCE_FAIL",
            format!(
                "{fail} case(s) returned verdict:fail: {}",
                failed_ids.join(", ")
            ),
        )]
    };
    let code = if ok { 0 } else { 1 };
    (
        envelope(ok, vec![Value::from(payload)], meta, vec![], vec![], errors),
        code,
    )
}

#[cfg(test)]
mod reconciliation_tests {
    use super::*;

    #[test]
    fn x01_rejects_one_sided_command_drift() {
        let caps = capabilities::build();
        let hand = caps["verbs"].as_object().unwrap().clone();
        let manifest = caps["parser_manifest"].clone();
        let derived = manifest["commands"].as_object().unwrap().clone();
        let globals = caps["global_flags"].clone();
        let derived_globals = manifest["global_flags"].clone();
        assert!(reconcile(&hand, &derived, &globals, &derived_globals));

        let mut parser_only = derived.clone();
        parser_only.insert("parser-only".into(), Value::Object(Map::new()));
        assert!(!reconcile(&hand, &parser_only, &globals, &derived_globals));

        let mut capabilities_only = hand.clone();
        capabilities_only.insert("capabilities-only".into(), Value::Object(Map::new()));
        assert!(!reconcile(
            &capabilities_only,
            &derived,
            &globals,
            &derived_globals
        ));
    }

    #[test]
    fn manifest_includes_global_aliases_and_is_the_name_source() {
        let names = crate::manifest::public_names();
        for name in [
            "content",
            "find",
            "--json",
            "--no-color",
            "--help",
            "-h",
            "--version",
            "-V",
        ] {
            assert!(names.contains(name), "missing parser name {name}");
        }
    }
}
